### ISSUE TITLE
Issues facing Yauk  library.

### ISSUE THREAD

**Issue by Furqan-code-tech** [awaisathar/yauk#7]
![image](https://user-images.githubusercontent.com/79757113/192358791-79ca781e-5623-41f5-8bf2-fa42bd837fe4.png)
![image](https://user-images.githubusercontent.com/79757113/192358855-81a7cb06-f3e3-4325-a6ac-21d393d8da3e.png)

**Comment by awaisathar** [comment]
Good to see this is being used :) Can you please post minimal code to reproduce this? Looks like `yauk.min.js` is not being loaded correctly and it should appear as a warning in the console.

**Comment by Furqan-code-tech** [comment]
Can you please took remote access of my system and see this issue in your free time?

If you can please tell me the time I will keep my self online.

Thankyou

**Comment by awaisathar** [comment]
I am afraid you'll have to do it via public access :)
I just checked and the demo seems to be okay so most probably it's a dev environment issue. Feel free to reopen this if the issue persists

**Comment by Furqan-code-tech** [comment]
Can you please took remote access of my systen hai see this issue in your
free time?

If you can please tell me the time I will keep my self online.

Thankyou
